CREATE TABLE IF NOT EXISTS shop_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  openId VARCHAR(64) NOT NULL,
  nickName VARCHAR(64) NOT NULL DEFAULT '',
  avatarUrl VARCHAR(512) NOT NULL DEFAULT '',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  name VARCHAR(64) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  location JSON NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_openId (openId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

